[Rule]
# >onyra
DOMAIN-KEYWORD, bps8m.onyra.cc
DOMAIN-KEYWORD, stream.onyra.uk
  
# >影迹
DOMAIN, emby1.123456789.lol
  
# >yunti
DOMAIN, emby.yunti.online

# >HKA
DOMAIN, hka-emby3.aliz.work

# >二次元
DOMAIN, media.nijigem.by

# >Nya
DOMAIN, emby.bangumi.ca

