# >影迹
DOMAIN, emby1.123456789.lol
# >yunti
DOMAIN, emby.yunti.online
# >HKA
DOMAIN, hka-emby3.aliz.work
# >二次元
DOMAIN, media.nijigem.by
# >Nya
DOMAIN, emby.bangumi.ca
#土匪
DOMAIN-SUFFIX, tufei.de
# 骑兵
DOMAIN-SUFFIX, emby.heisi.org
#jv
DOMAIN-SUFFIX,tanhuatv.site
#zn
DOMAIN-SUFFIX, emby.zn.al

HOST,emby.enjoyit.eu.org
HOST,emby.lcloud.wiki
HOST,notnetflix.cos.cat
HOST-SUFFIX,123456.al
HOST-SUFFIX,285286.xyz
HOST-SUFFIX,agahk1.jmsooo.com
HOST-SUFFIX,agajp1.jmsooo.com
HOST-SUFFIX,agasg1.jmsooo.com
HOST-SUFFIX,aws.jmsooo.com
HOST-SUFFIX,cf1.jmsooo.com
HOST-SUFFIX,cristiamo.xyz
HOST-SUFFIX,emby.cjpc.cc
HOST-SUFFIX,emby.cjpc.tv
HOST-SUFFIX,emby.cjpc.xyz
HOST-SUFFIX,emby.cristiamo.top
HOST-SUFFIX,emby.flowercloud.yt
HOST-SUFFIX,emby.immtel.com
HOST-SUFFIX,emby.maying.club
HOST-SUFFIX,emby.mcwy.me
HOST-SUFFIX,emby.mdss.cloud
HOST-SUFFIX,emby.neko.edu.rs
HOST-SUFFIX,emby.nexitally.com
HOST-SUFFIX,emby.nyancat.net
HOST-SUFFIX,emby.ok.edu.hk
HOST-SUFFIX,emby.paoche.ooo
HOST-SUFFIX,emby.prprcloud.com
HOST-SUFFIX,emby.wtf
HOST-SUFFIX,emby.xeton.dev
HOST-SUFFIX,emby.ytoo.li
HOST-SUFFIX,embymv.tk
HOST-SUFFIX,embyplus.org
HOST-SUFFIX,embyserver.ga
HOST-SUFFIX,hinet.jmsooo.com
HOST-SUFFIX,imetyou.top
HOST-SUFFIX,jellyfin.asia
HOST-SUFFIX,jellyfin.xeton.dev
HOST-SUFFIX,line.emby.men
HOST-SUFFIX,mickeycloud.com
HOST-SUFFIX,movie.xeton.dev
HOST-SUFFIX,ntt1.jmsooo.com
HOST-SUFFIX,ohhhh.org
HOST-SUFFIX,peachmv.me
HOST-SUFFIX,pilipiliultra.com
HOST-SUFFIX,plusmedia.site
HOST-SUFFIX,poloemby.xyz
HOST-SUFFIX,pornemby.club
HOST-SUFFIX,servers.xeton.dev
HOST-SUFFIX,xmsl.org
HOST-KEYWORD,emby.wtf
HOST-KEYWORD,jmsooo
HOST-KEYWORD,odysseyplus
